#!/usr/bin/env bash

# This script is for when you totally screw up and want to just start over.
# It removes everything in the current directory, and reclones the repo.
# This deletes *everything* in the current directory, so it can be extreamly
# dangerous.

REMOTE="$(git remote -v 2> /dev/null | grep "origin\s.\+(fetch)" | awk '{print $2}')"
if [ -n "$REMOTE" ]; then
    find . -mindepth 1 -delete
    git clone $REMOTE .
fi
